### ISSUE TITLE
Attempting to open or generate a world in MCEdit crashes

### ISSUE THREAD

**Issue by Qworg** [mcgreentn/MCAI#2]
I'm on Linux - Ubuntu 16.04 LTS - 4.4.0-121-generic.

Steps to reproduce: 
* Run mcedit.sh, then attempt to generate or load a world.

```
[   ERROR][                  root.py:1049]:MCEdit version Unified v1.5.6.0 %s Minecraft 1.8-1.11.2 | PE 0.11
Traceback (most recent call last):
  File "mcedit.py", line 1109, in <module>
    main(sys.argv)
  File "mcedit.py", line 1046, in main
    MCEdit.main()
  File "mcedit.py", line 890, in main
    rootwidget.run()
  File "/home/qworg/Development/gdmc/GDMC/albow/root.py", line 168, in run
    self.run_modal(None)
  File "/home/qworg/Development/gdmc/GDMC/albow/root.py", line 303, in run_modal
    last_mouse_event_handler.handle_mouse('mouse_up', event)
  File "/home/qworg/Development/gdmc/GDMC/albow/widget.py", line 403, in handle_mouse
    self.call_handler(name, event)
  File "/home/qworg/Development/gdmc/GDMC/albow/widget.py", line 485, in call_handler
    return method(*args)
  File "/home/qworg/Development/gdmc/GDMC/albow/controls.py", line 240, in mouse_up
    self.call_handler('action')
  File "/home/qworg/Development/gdmc/GDMC/albow/widget.py", line 485, in call_handler
    return method(*args)
  File "/home/qworg/Development/gdmc/GDMC/albow/file_opener.py", line 144, in promptOpenAndLoad
    filename = mcplatform.askOpenFile(schematics=True)
  File "/home/qworg/Development/gdmc/GDMC/mcplatform.py", line 283, in askOpenFile
    filename = _askOpen(suffixes)
  File "/home/qworg/Development/gdmc/GDMC/mcplatform.py", line 281, in _askOpen
    return request_old_filename(suffixes=_suffixes, directory=iDir)
  File "/home/qworg/Development/gdmc/GDMC/albow/file_dialogs.py", line 546, in request_old_filename
    dlog = FileOpenDialog(suffixes=suffixes)
  File "/home/qworg/Development/gdmc/GDMC/albow/file_dialogs.py", line 322, in __init__
    tree = FSTree(self, inner_width=250, directory='/')
  File "/home/qworg/Development/gdmc/GDMC/albow/file_dialogs.py", line 193, in __init__
    d[name] = self.parse_path(name, os.path.join(dirpath, name))
  File "/home/qworg/Development/gdmc/GDMC/albow/file_dialogs.py", line 263, in parse_path
    for _a, fs, _b in cont:
  File "/home/qworg/miniconda3/envs/gdmc/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/home/qworg/miniconda3/envs/gdmc/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf8 in position 1: ordinal not in range(128)

==================================
			  MCEdit has crashed
==================================
```

**Comment by mcgreentn** [comment]
Anytime that I've struggled to generate worlds, I've always been able to trace it back to a mismatch of where MCEdit thinks Minecraft was installed and where it is actually installed. MCEdit uses Minecraft's world generator by default, so if it can't find it, it actually has 0 error handling for it (thus a crash).

Check to make sure that Minecraft is installed on the machine, and that MCEdit is pointing to it. I'm actually not sure where the default installation is for a Linux machine..
